############# English navigation ##############

# main menu
[[main]]
name = "Главная"
url = "/"
weight = 1

[[main]]
name = "Сведения об образовательной организации"
url = "/education"
weight = 2

[[main]]
name = "Программа обучения"
url = "/programma"
weight = 3


# footer menu
[[footer]]
name = "Политика конфиденциальности"
url = "/privacy-policy"
weight = 1

[[footer]]
name = "Министерство науки и высшего образования РФ"
url = "https://www.minobrnauki.gov.ru"
weight = 2

[[footer]]
name = "Министерство просвещения РФ"
url = "https://edu.gov.ru"
weight = 3
